// Test setup
import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

// Initialize i18n with English translations for tests
// This ensures t() returns actual strings rather than key names
i18n.use(initReactI18next).init({
  resources: {
    en: {
      actions: {
        create: 'Create',
        edit: 'Edit',
        delete: 'Delete',
        save: 'Save changes',
        cancel: 'Cancel',
        saving: 'Saving…',
        confirm: 'Confirm',
        restore: 'Restore',
        archive: 'Archive',
        delete_permanent: 'Delete permanently',
        replicate: 'Replicate',
        please_wait: 'Please wait…',
      },
      messages: {
        record_created: 'Record created successfully.',
        record_updated: 'Record updated successfully.',
        record_deleted: 'Record deleted successfully.',
        record_restored: 'Record restored successfully.',
        record_not_found: 'Record not found.',
        loading: 'Loading…',
        error_schema: 'Error loading resource schema.',
        error_update: 'Error updating record.',
        error_create: 'Error creating record.',
        error_delete: 'Error deleting record.',
        error_restore: 'Error restoring record.',
        invalid_field: 'Invalid',
        archived: 'Archived',
        archive_confirm: 'This record will be archived and can be restored later.',
        delete_confirm: 'This action is permanent and cannot be undone. Are you sure?',
        yes: 'Yes',
        no: 'No',
        active: 'Active',
        inactive: 'Inactive',
      },
      navigation: {
        dashboard: 'Dashboard',
        footer: 'Martis Admin Engine',
        toggle_theme: 'Toggle theme',
        logout: 'Sign out',
        resources: 'Resources',
        detail: 'Detail',
        create: 'Create',
        edit: 'Edit',
        index: 'Index',
        profile: 'Profile',
      },
      resources: {
        new: 'New {{label}}',
        search: 'Search {{label}}…',
        selected: '{{count}} selected',
        edit: 'Edit {{label}}',
        loading: 'Loading…',
        registered: 'Registered resources',
        welcome: 'Welcome to Martis Admin Engine.',
        hello: 'Hello, {{name}}',
        no_records: 'No records found.',
      },
      auth: {
        title: 'Martis Admin',
        email: 'Email',
        password: 'Password',
        sign_in: 'Sign in',
        signing_in: 'Signing in…',
        error: 'Error signing in.',
        session_ended: 'Session ended.',
      },
      profile: {
        title: 'My Profile',
        account: 'Account Information',
        password: 'Change Password',
        security: 'Two-Factor Authentication',
        avatar: 'Profile Picture',
        name: 'Name',
        email: 'Email',
        save: 'Save Changes',
        saving: 'Saving…',
        saved: 'Changes saved successfully.',
        error: 'An error occurred. Please try again.',
        current_password: 'Current Password',
        new_password: 'New Password',
        confirm_password: 'Confirm New Password',
        password_updated: 'Password updated successfully.',
        password_mismatch: 'Passwords do not match.',
        password_min: 'Password must be at least 8 characters.',
        update_password: 'Update Password',
        updating_password: 'Updating…',
        avatar_upload: 'Upload Photo',
        avatar_remove: 'Remove Photo',
        avatar_change: 'Change Photo',
        avatar_uploading: 'Uploading…',
        avatar_uploaded: 'Photo updated successfully.',
        avatar_removed: 'Photo removed.',
        avatar_invalid_type: 'Invalid file type. Use JPEG, PNG or WebP.',
        avatar_too_large: 'File too large. Maximum size: {{size}} MB.',
        '2fa_enable': 'Enable Two-Factor Authentication',
        '2fa_disable': 'Disable Two-Factor Authentication',
        '2fa_enabled_badge': 'Enabled',
        '2fa_disabled_badge': 'Disabled',
        '2fa_wizard_title': 'Set Up Two-Factor Authentication',
        '2fa_scan_qr': 'Scan QR Code',
        '2fa_scan_instructions': 'Scan this QR code with your authenticator app.',
        '2fa_manual_entry': 'Or enter the secret key manually:',
        '2fa_next': 'Next',
        '2fa_enter_code': 'Enter Verification Code',
        '2fa_code_instructions': 'Enter the 6-digit code from your authenticator app.',
        '2fa_code_label': 'Authentication Code',
        '2fa_verify': 'Verify',
        '2fa_verifying': 'Verifying…',
        '2fa_invalid_code': 'Invalid code. Please try again.',
        '2fa_recovery_codes': 'Recovery Codes',
        '2fa_recovery_instructions': 'Save these recovery codes in a safe place.',
        '2fa_copy_codes': 'Copy Codes',
        '2fa_codes_copied': 'Codes copied!',
        '2fa_done': 'Done',
        '2fa_enabled_success': 'Two-factor authentication enabled.',
        '2fa_disabled_success': 'Two-factor authentication disabled.',
        '2fa_view_recovery': 'View Recovery Codes',
        '2fa_challenge_title': 'Two-Factor Authentication',
        '2fa_challenge_instructions': 'Please enter the authentication code.',
        '2fa_challenge_submit': 'Verify',
        '2fa_challenge_submitting': 'Verifying…',
        '2fa_use_recovery_code': 'Use a recovery code',
        '2fa_use_otp': 'Use authenticator code',
        '2fa_recovery_placeholder': 'Recovery code',
        '2fa_otp_placeholder': '6-digit code',
        '2fa_challenge_failed': 'Invalid code. Please try again.',
        profile: 'Profile',
      },
    },
  },
  lng: 'en',
  fallbackLng: 'en',
  interpolation: { escapeValue: false },
  react: { useSuspense: false },
})
