/**
 * Type entry for the `react-router-dom` shim
 * (`stubs/extensions/react-router-dom-shim.mjs.stub`). `npm run build:types`
 * bundles it into `react-router-dom-shim.d.mts.stub`: the names the shim
 * exports, the types of the library, and the whole module as its default
 * export (the shim's default is `window.Martis.runtime.reactRouterDom`, the
 * host's module namespace).
 *
 * The host runs React Router 7, where `react-router-dom` is a re-export of
 * `react-router`: the values come from `@/lib/reactRouterDom` (the module the
 * runtime serves, with the DOM `RouterProvider`), the types from
 * `react-router`.
 */
import * as ReactRouterDom from '@/lib/reactRouterDom'

export {
  Link,
  NavLink,
  Outlet,
  Navigate,
  Route,
  Routes,
  BrowserRouter,
  HashRouter,
  RouterProvider,
  useNavigate,
  useParams,
  useSearchParams,
  useLocation,
  useMatch,
  useResolvedPath,
  useNavigationType,
  generatePath,
  matchPath,
  matchRoutes,
  createBrowserRouter,
  createHashRouter,
  createMemoryRouter,
} from '@/lib/reactRouterDom'

// Every type of the library (its interfaces and type aliases), type-only: an
// import of a type is erased from the build, so it needs no shim export, and
// the consumer's tsconfig sends the specifier here instead of to
// `node_modules`. A class or enum the shim does not export (`NavigationType`) is
// not among them: rollup-plugin-dts would declare it as a value, which the
// build does not have. The default export, the host's module, holds it.
export type {
  ActionFunction,
  ActionFunctionArgs,
  AppLoadContext,
  AwaitProps,
  BaseRouteObject,
  Blocker,
  BlockerFunction,
  BrowserRouterProps,
  ClientActionFunction,
  ClientActionFunctionArgs,
  ClientInstrumentation,
  ClientLoaderFunction,
  ClientLoaderFunctionArgs,
  ClientOnErrorFunction,
  Cookie,
  CookieOptions,
  CookieParseOptions,
  CookieSerializeOptions,
  CookieSignatureOptions,
  CreateRequestHandlerFunction,
  DOMRouterOpts,
  DataRouteMatch,
  DataRouteObject,
  DataRouter,
  DataStrategyFunction,
  DataStrategyFunctionArgs,
  DataStrategyMatch,
  DataStrategyResult,
  DiscoverBehavior,
  EntryContext,
  ErrorResponse,
  Fetcher,
  FetcherFormProps,
  FetcherSubmitFunction,
  FetcherSubmitOptions,
  FetcherWithComponents,
  FlashSessionData,
  FormEncType,
  FormMethod,
  FormProps,
  Future,
  GetScrollPositionFunction,
  GetScrollRestorationKeyFunction,
  HTMLFormMethod,
  HandleDataRequestFunction,
  HandleDocumentRequestFunction,
  HandleErrorFunction,
  HashRouterProps,
  HeadersArgs,
  HeadersFunction,
  HistoryRouterProps,
  HtmlLinkDescriptor,
  HydrationState,
  IndexRouteObject,
  IndexRouteProps,
  InitialEntry,
  InstrumentRequestHandlerFunction,
  InstrumentRouteFunction,
  InstrumentRouterFunction,
  InstrumentationHandlerResult,
  IsCookieFunction,
  IsSessionFunction,
  LayoutRouteProps,
  LazyRouteFunction,
  LinkDescriptor,
  LinkProps,
  LinksFunction,
  LinksProps,
  LoaderFunction,
  LoaderFunctionArgs,
  Location,
  MemoryRouterOpts,
  MemoryRouterProps,
  MetaArgs,
  MetaDescriptor,
  MetaFunction,
  MiddlewareFunction,
  NavLinkProps,
  NavLinkRenderProps,
  NavigateFunction,
  NavigateOptions,
  NavigateProps,
  Navigation,
  NavigationStates,
  Navigator,
  NonIndexRouteObject,
  OutletProps,
  PageLinkDescriptor,
  ParamKeyValuePair,
  ParamParseKey,
  Params,
  PatchRoutesOnNavigationFunction,
  PatchRoutesOnNavigationFunctionArgs,
  Path,
  PathMatch,
  PathParam,
  PathPattern,
  PathRouteProps,
  PrefetchBehavior,
  RedirectFunction,
  Register,
  RelativeRoutingType,
  RequestHandler,
  RevalidationState,
  RouteMatch,
  RouteObject,
  RouteProps,
  RouterContext,
  RouterFetchOptions,
  RouterInit,
  RouterNavigateOptions,
  RouterProps,
  RouterProviderProps,
  RouterState,
  RouterSubscriber,
  RoutesProps,
  RoutesTestStubProps,
  ScriptsProps,
  ScrollRestorationProps,
  ServerBuild,
  ServerEntryModule,
  ServerInstrumentation,
  ServerRouterProps,
  Session,
  SessionData,
  SessionIdStorageStrategy,
  SessionStorage,
  SetURLSearchParams,
  ShouldRevalidateFunction,
  ShouldRevalidateFunctionArgs,
  StaticHandler,
  StaticHandlerContext,
  StaticRouterProps,
  StaticRouterProviderProps,
  SubmitFunction,
  SubmitOptions,
  SubmitTarget,
  To,
  UIMatch,
  UNSAFE_AssetsManifest,
  UNSAFE_MiddlewareEnabled,
  UNSAFE_RouteModules,
  URLSearchParamsInit,
  unstable_BrowserCreateFromReadableStreamFunction,
  unstable_DecodeActionFunction,
  unstable_DecodeFormStateFunction,
  unstable_DecodeReplyFunction,
  unstable_EncodeReplyFunction,
  unstable_LoadServerActionFunction,
  unstable_RSCHydratedRouterProps,
  unstable_RSCManifestPayload,
  unstable_RSCMatch,
  unstable_RSCPayload,
  unstable_RSCRenderPayload,
  unstable_RSCRouteConfig,
  unstable_RSCRouteConfigEntry,
  unstable_RSCRouteManifest,
  unstable_RSCRouteMatch,
  unstable_RSCStaticRouterProps,
  unstable_RouterState,
  unstable_RouterStateActiveVariant,
  unstable_RouterStatePendingVariant,
  unstable_SSRCreateFromReadableStreamFunction,
  unstable_SerializesTo,
} from 'react-router'

export default ReactRouterDom
