/**
 * Type entry for the `@tanstack/react-query` shim
 * (`stubs/extensions/tanstack-react-query-shim.mjs.stub`).
 * `npm run build:types` bundles it into
 * `tanstack-react-query-shim.d.mts.stub`: the names the shim exports, the
 * types of the library, and the host's module namespace as the default
 * export.
 */
import * as TanstackReactQuery from '@tanstack/react-query'
import type { DefaultError, QueryBooleanOption, QueryKey } from '@tanstack/react-query'

export {
  useQuery,
  useMutation,
  useQueryClient,
  useInfiniteQuery,
  useIsFetching,
  useIsMutating,
  useQueries,
  useSuspenseQuery,
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'

// Every type of the library (its interfaces and type aliases), type-only: an
// import of a type is erased from the build, so it needs no shim export, and
// the consumer's tsconfig sends the specifier here instead of to
// `node_modules`. A class or enum the shim does not export (`QueryCache`) is
// not among them: rollup-plugin-dts would declare it as a value, which the
// build does not have. The default export, the host's module, holds it.
export type {
  AnyDataTag,
  AnyUseBaseQueryOptions,
  AnyUseInfiniteQueryOptions,
  AnyUseMutationOptions,
  AnyUseQueryOptions,
  AnyUseSuspenseInfiniteQueryOptions,
  AnyUseSuspenseQueryOptions,
  CancelOptions,
  DataTag,
  DefaultedInfiniteQueryObserverOptions,
  DefaultedQueryObserverOptions,
  DefaultError,
  DefaultOptions,
  DefinedInfiniteQueryObserverResult,
  DefinedInitialDataInfiniteOptions,
  DefinedInitialDataOptions,
  DefinedQueryObserverResult,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  DehydratedState,
  DehydrateOptions,
  DistributiveOmit,
  EnsureInfiniteQueryDataOptions,
  EnsureQueryDataOptions,
  FetchInfiniteQueryOptions,
  FetchNextPageOptions,
  FetchPreviousPageOptions,
  FetchQueryOptions,
  FetchStatus,
  GetNextPageParamFunction,
  GetPreviousPageParamFunction,
  HydrateOptions,
  HydrationBoundaryProps,
  InferDataFromTag,
  InferErrorFromTag,
  InfiniteData,
  InfiniteQueryExecuteOptions,
  InfiniteQueryObserverBaseResult,
  InfiniteQueryObserverLoadingErrorResult,
  InfiniteQueryObserverLoadingResult,
  InfiniteQueryObserverOptions,
  InfiniteQueryObserverPendingResult,
  InfiniteQueryObserverPlaceholderResult,
  InfiniteQueryObserverRefetchErrorResult,
  InfiniteQueryObserverResult,
  InfiniteQueryObserverSuccessResult,
  InfiniteQueryPageParamsOptions,
  InitialDataFunction,
  InitialPageParam,
  InvalidateOptions,
  InvalidateQueryFilters,
  ManagedTimerId,
  MutateFunction,
  MutateFunctionRest,
  MutateOptions,
  MutationCacheConfig,
  MutationCacheNotifyEvent,
  MutationFilters,
  MutationFunction,
  MutationFunctionContext,
  MutationKey,
  MutationMeta,
  MutationObserverBaseResult,
  MutationObserverErrorResult,
  MutationObserverIdleResult,
  MutationObserverLoadingResult,
  MutationObserverOptions,
  MutationObserverResult,
  MutationObserverSuccessResult,
  MutationOptions,
  MutationScope,
  MutationState,
  MutationStatus,
  NetworkMode,
  NonUndefinedGuard,
  NotifyEvent,
  NotifyEventType,
  NotifyOnChangeProps,
  OmitKeyof,
  Override,
  PlaceholderDataFunction,
  QueriesObserverOptions,
  QueriesOptions,
  QueriesPlaceholderDataFunction,
  QueriesResults,
  QueryBooleanOption,
  QueryCacheConfig,
  QueryCacheNotifyEvent,
  QueryClientConfig,
  QueryClientProviderProps,
  QueryErrorClearResetFunction,
  QueryErrorIsResetFunction,
  QueryErrorResetBoundaryFunction,
  QueryErrorResetBoundaryProps,
  QueryErrorResetFunction,
  QueryExecuteOptions,
  QueryFilters,
  QueryFunction,
  QueryFunctionContext,
  QueryKey,
  QueryKeyHashFunction,
  QueryKeyWithDataTag,
  QueryMeta,
  QueryObserverBaseResult,
  QueryObserverLoadingErrorResult,
  QueryObserverLoadingResult,
  QueryObserverOptions,
  QueryObserverPendingResult,
  QueryObserverPlaceholderResult,
  QueryObserverRefetchErrorResult,
  QueryObserverResult,
  QueryObserverSuccessResult,
  QueryOptions,
  QueryPersister,
  QueryState,
  QueryStatus,
  RefetchOptions,
  RefetchQueryFilters,
  Register,
  ResetOptions,
  ResultOptions,
  SetDataOptions,
  SkipToken,
  StaleTime,
  StaleTimeFunction,
  SuspenseQueriesOptions,
  SuspenseQueriesResults,
  ThrowOnError,
  TimeoutCallback,
  TimeoutProvider,
  UndefinedInitialDataInfiniteOptions,
  UndefinedInitialDataOptions,
  UnsetMarker,
  UnusedSkipTokenInfiniteOptions,
  UnusedSkipTokenOptions,
  Updater,
  UseBaseMutationResult,
  UseBaseQueryOptions,
  UseBaseQueryResult,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutateAsyncFunction,
  UseMutateFunction,
  UseMutationOptions,
  UseMutationResult,
  UsePrefetchInfiniteQueryOptions,
  UsePrefetchQueryOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
  WithRequired,
} from '@tanstack/react-query'

// Two types @tanstack/query-core dropped in 5.x minors, kept for the
// extensions that import them from `@tanstack/react-query` (these
// declarations are the typing surface of an extension build):
//
// - `Enabled` was renamed `QueryBooleanOption` (the same definition: a boolean,
//   or a function of the query returning one).
// - `NoInfer` was removed in 5.100.13 in favour of TypeScript's built-in
//   `NoInfer` (TS >= 5.4). The alias below is that built-in, declared under
//   another name and exported as `NoInfer`, so the library types that use the
//   global `NoInfer` keep resolving to it in the bundled declarations.
//
// Drop both at the next breaking release of the shim declarations.
export type Enabled<
  TQueryFnData = unknown,
  TError = DefaultError,
  TData = TQueryFnData,
  TQueryKey extends QueryKey = QueryKey,
> = QueryBooleanOption<TQueryFnData, TError, TData, TQueryKey>

type NoInferCompat<T> = NoInfer<T>
export type { NoInferCompat as NoInfer }

export default TanstackReactQuery
