import type { IconProps } from "@phosphor-icons/react"
import {
  // Common admin/CRUD icons
  Database,
  Article,
  ArticleNyTimes,
  Newspaper,
  NewspaperClipping,
  Tag,
  Users,
  UsersThree,
  UserCircle,
  User,
  Folder,
  FolderSimple,
  FolderOpen,
  Gear,
  GearSix,
  ChartBar,
  ChartLine,
  ChartPie,
  ShoppingCart,
  ShoppingBag,
  CreditCard,
  MapPin,
  FileText,
  File,
  FilePdf,
  FileDoc,
  FileXls,
  FileCsv,
  FileCode,
  FileZip,
  Image,
  Images,
  Camera,
  Bell,
  BellRinging,
  ChatCircle,
  ChatText,
  Envelope,
  EnvelopeSimple,
  Globe,
  GlobeSimple,
  House,
  Buildings,
  Calendar,
  CalendarBlank,
  Clock,
  ClockCountdown,
  Star,
  Heart,
  BookOpen,
  BookmarkSimple,
  Lightbulb,
  Flag,
  Lock,
  Key,
  Shield,
  ShieldCheck,
  Eye,
  Link,
  Paperclip,
  Package,
  Truck,
  Receipt,
  CurrencyDollar,
  Wallet,

  Storefront,
  Megaphone,
  PaintBrush,
  Palette,
  Code,
  Terminal,
  Wrench,
  Plug,
  Lightning,
  Sparkle,
  Trophy,
  Medal,
  Crown,
  Percent,
  Hash,
  At,
  ListBullets,
  ListChecks,
  Table,
  Rows,
  Columns,
  SquaresFour,
  GridFour,
  Stack,
  TreeStructure,
  Share,
  Export,
  Download,
  Upload,
  Cloud,
  Desktop,
  HardDrives,
  Cpu,
  Notebook,
  Note,
  NotePencil,
  PencilSimple,
  Trash,
  Plus,
  Minus,
  Check,
  X,
  Warning,
  Info,
  Question,
  ArrowRight,
  ArrowLeft,
  CaretDown,
  CaretUp,
  CaretRight,
  MagnifyingGlass,
  Funnel,
  SlidersHorizontal,
  Sliders,
} from "@phosphor-icons/react"

/**
 * Static icon map — maps lowercase/kebab names to Phosphor components.
 * This approach works reliably with Vite production builds (import * does NOT).
 */
const iconMap: Record<string, React.ComponentType<IconProps>> = {
  // Resources & data
  database: Database,
  article: Article,
  "article-ny-times": ArticleNyTimes,
  newspaper: Newspaper,
  "newspaper-clipping": NewspaperClipping,
  tag: Tag,
  // People
  users: Users,
  "users-three": UsersThree,
  "user-circle": UserCircle,
  user: User,
  // Files & folders
  folder: Folder,
  folders: FolderSimple,
  "folder-simple": FolderSimple,
  "folder-open": FolderOpen,
  file: File,
  "file-text": FileText,
  "file-pdf": FilePdf,
  "file-doc": FileDoc,
  "file-xls": FileXls,
  "file-csv": FileCsv,
  "file-code": FileCode,
  "file-zip": FileZip,
  // Media
  image: Image,
  images: Images,
  camera: Camera,
  // Settings
  gear: Gear,
  "gear-six": GearSix,
  wrench: Wrench,
  sliders: Sliders,
  "sliders-horizontal": SlidersHorizontal,
  // Charts
  "chart-bar": ChartBar,
  "chart-line": ChartLine,
  "chart-pie": ChartPie,
  // Commerce
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  "credit-card": CreditCard,
  storefront: Storefront,
  receipt: Receipt,
  "currency-dollar": CurrencyDollar,
  wallet: Wallet,
  package: Package,
  truck: Truck,
  percent: Percent,
  // Communication
  chat: ChatCircle,
  "chat-circle": ChatCircle,
  "chat-text": ChatText,
  envelope: Envelope,
  "envelope-simple": EnvelopeSimple,
  bell: Bell,
  "bell-ringing": BellRinging,
  megaphone: Megaphone,
  // Navigation & location
  "map-pin": MapPin,
  globe: Globe,
  "globe-simple": GlobeSimple,
  house: House,
  buildings: Buildings,
  // Time & date
  calendar: Calendar,
  "calendar-blank": CalendarBlank,
  clock: Clock,
  "clock-countdown": ClockCountdown,
  // Engagement
  star: Star,
  heart: Heart,
  trophy: Trophy,
  medal: Medal,
  crown: Crown,
  flag: Flag,
  sparkle: Sparkle,
  // Knowledge
  "book-open": BookOpen,
  "bookmark-simple": BookmarkSimple,
  lightbulb: Lightbulb,
  notebook: Notebook,
  note: Note,
  "note-pencil": NotePencil,
  // Security
  lock: Lock,
  key: Key,
  shield: Shield,
  "shield-check": ShieldCheck,
  eye: Eye,
  // Misc
  link: Link,
  paperclip: Paperclip,
  code: Code,
  terminal: Terminal,
  plug: Plug,
  lightning: Lightning,
  "paint-brush": PaintBrush,
  palette: Palette,
  hash: Hash,
  at: At,
  // Layout
  "list-bullets": ListBullets,
  "list-checks": ListChecks,
  table: Table,
  rows: Rows,
  columns: Columns,
  "squares-four": SquaresFour,
  "grid-four": GridFour,
  stack: Stack,
  "tree-structure": TreeStructure,
  // Actions
  share: Share,
  export: Export,
  download: Download,
  upload: Upload,
  "pencil-simple": PencilSimple,
  trash: Trash,
  plus: Plus,
  minus: Minus,
  check: Check,
  x: X,
  funnel: Funnel,
  "magnifying-glass": MagnifyingGlass,
  // Cloud & infra
  cloud: Cloud,
  server: Desktop,
  "hard-drives": HardDrives,
  cpu: Cpu,
  // Status
  warning: Warning,
  info: Info,
  question: Question,
  // Arrows
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "caret-down": CaretDown,
  "caret-up": CaretUp,
  "caret-right": CaretRight,
}

/**
 * Also map PascalCase names so both `tag` and `Tag` work.
 */
for (const [key, val] of Object.entries({ ...iconMap })) {
  // Add PascalCase variant
  const pascal = key
    .split("-")
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("")
  if (!iconMap[pascal]) {
    iconMap[pascal] = val
  }
}

interface ResourceIconProps {
  iconName: string | null | undefined
  size?: number
  className?: string
  weight?: IconProps["weight"]
}

export function ResourceIcon({ iconName, size, className, weight }: ResourceIconProps) {
  const name = iconName ?? "database"
  const Icon = iconMap[name] ?? iconMap[name.toLowerCase()] ?? Database
  return <Icon size={size} className={className} weight={weight} />
}
