<?php

namespace Martis\Console;

use Illuminate\Console\Command;

class ThemeMakeCommand extends Command
{
    protected $signature = 'martis:theme {name? : The theme name (default: custom)}';

    protected $description = 'Scaffold a custom Martis theme with dark and light mode variables';

    /**
     * Handle.
     */
    public function handle(): int
    {
        /** @var string $name */
        $name = $this->argument('name') ?? 'custom';
        $name = strtolower((string) preg_replace('/[^a-zA-Z0-9_-]/', '-', $name));

        // 1. Create source CSS in resources/
        $dir = resource_path('css/martis');
        $path = $dir.'/'.$name.'.css';

        if (! is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        if (file_exists($path) && ! $this->confirm("Theme '{$name}.css' already exists. Overwrite?")) {
            $this->components->warn('Aborted.');

            return self::FAILURE;
        }

        file_put_contents($path, $this->themeStub($name));
        $this->components->info("Theme created: resources/css/martis/{$name}.css");

        // 2. Publish to public/vendor/martis/themes/
        $publicDir = public_path('vendor/martis/themes');
        if (! is_dir($publicDir)) {
            mkdir($publicDir, 0755, true);
        }
        copy($path, $publicDir.'/'.$name.'.css');
        $this->components->info("Published to: public/vendor/martis/themes/{$name}.css");

        // 3. Update config/martis.php theme.name
        $configPath = config_path('martis.php');
        if (file_exists($configPath)) {
            $configContent = file_get_contents($configPath);

            if ($configContent === false) {
                return self::SUCCESS;
            }

            if (str_contains($configContent, "'name' =>")) {
                // Update existing name value
                $configContent = (string) preg_replace(
                    "/('name'\s*=>\s*)(env\([^)]+\)|'[^']*'|null)/",
                    "'{$name}'",
                    $configContent,
                    1 // only first occurrence within theme block
                );
            } else {
                // Add name key after allowToggle line
                $configContent = (string) preg_replace(
                    "/(\s*'allowToggle'\s*=>.*?,)/",
                    "\n        'name' => '{$name}',",
                    $configContent
                );
            }

            file_put_contents($configPath, (string) $configContent);
            $this->components->info("Config updated: config/martis.php theme.name = '{$name}'");
        }

        $this->newLine();
        $this->components->twoColumnDetail('<fg=green>Done</>');
        $this->newLine();
        $this->line('  1. Edit the CSS variables in <comment>public/vendor/martis/themes/'.$name.'.css</comment>');
        $this->line('  2. Changes take effect immediately (plain CSS, no rebuild needed).');
        $this->line('  3. Or change theme in <comment>config/martis.php</comment>:');
        $this->newLine();
        $this->line("     <comment>'theme' => ['name' => '{$name}']</comment>");
        $this->newLine();
        $this->line('  To revert to default theme: set name to null in config.');
        $this->newLine();

        return self::SUCCESS;
    }

    private function themeStub(string $name): string
    {
        return <<<CSS
/*
 * Martis Theme: {$name}
 *
 * Every CSS variable used by Martis is listed below.
 * Edit any value and re-run: php artisan martis:theme {$name}
 *
 * Generated by: php artisan martis:theme {$name}
 */

/* ── Dark Mode (default) ─────────────────────────────────────── */
:root {
  /* ▸ Background layers */
  --martis-bg:            #1b2332;
  --martis-surface:       #1e293b;
  --martis-surface-alt:   #283548;
  --martis-sidebar:       #111827;
  --martis-topbar:        #1e293b;
  --martis-card:          #1e293b;
  --martis-input-bg:      #111827;

  /* ▸ Borders */
  --martis-border:        #334155;

  /* ▸ Text */
  --martis-text:          #e2e8f0;
  --martis-text-muted:    #94a3b8;

  /* ▸ Accent (brand color — buttons, links, focus rings) */
  --martis-accent:        #6366f1;
  --martis-accent-hover:  #4f46e5;
  --martis-accent-active: #4338ca;
  --martis-accent-bg-light: rgba(99, 102, 241, 0.08);
  --martis-accent-bg:     rgba(99, 102, 241, 0.15);
  --martis-focus-ring:    rgba(99, 102, 241, 0.2);

  /* ▸ Semantic colors (solid) */
  --martis-success:       #22c55e;
  --martis-success-hover: #16a34a;
  --martis-warning:       #f59e0b;
  --martis-warning-hover: #d97706;
  --martis-danger:        #ef4444;
  --martis-danger-hover:  #dc2626;
  --martis-info:          #3b82f6;
  --martis-info-hover:    #2563eb;

  /* ▸ Semantic backgrounds & text (badges, alerts) */
  --martis-success-bg:    rgba(34, 197, 94, 0.15);
  --martis-success-text:  #86efac;
  --martis-warning-bg:    rgba(245, 158, 11, 0.15);
  --martis-warning-text:  #fcd34d;
  --martis-danger-bg:     rgba(239, 68, 68, 0.15);
  --martis-danger-text:   #fca5a5;
  --martis-info-bg:       rgba(59, 130, 246, 0.15);
  --martis-info-text:     #93c5fd;

  /* ▸ Interactive states */
  --martis-hover:         rgba(255, 255, 255, 0.05);
  --martis-active:        rgba(255, 255, 255, 0.1);

  /* ▸ Search overlay */
  --martis-search-bg:     rgba(255, 255, 255, 0.06);
  --martis-search-border: rgba(255, 255, 255, 0.1);

  /* ▸ Overlays & shadows */
  --martis-overlay:       rgba(0, 0, 0, 0.5);
  --martis-peek-shadow:   0 2px 8px rgba(0, 0, 0, 0.20);
  --martis-shadow-sm:     0 1px 2px rgba(0, 0, 0, 0.1);
  --martis-shadow-md:     0 4px 6px -1px rgba(0, 0, 0, 0.2), 0 2px 4px -1px rgba(0, 0, 0, 0.1);
  --martis-shadow-lg:     0 10px 15px -3px rgba(0, 0, 0, 0.3), 0 4px 6px -2px rgba(0, 0, 0, 0.15);

  /* ▸ DataTable */
  --martis-row-even:              rgba(30, 41, 59, 0.5);
  --martis-row-hover:             rgba(51, 65, 85, 0.5);
  --martis-table-header-bg:       rgba(99, 102, 241, 0.1);
  --martis-table-header-text:     #c7d2fe;
  --martis-table-header-border:   rgba(99, 102, 241, 0.35);

  /* ▸ Badge variants (legacy — kept for backward compatibility) */
  --martis-badge-info-bg:         rgba(99, 102, 241, 0.15);
  --martis-badge-info-text:       #a5b4fc;
  --martis-badge-info-border:     rgba(99, 102, 241, 0.3);
  --martis-badge-success-bg:      rgba(34, 197, 94, 0.15);
  --martis-badge-success-text:    #86efac;
  --martis-badge-success-border:  rgba(34, 197, 94, 0.3);
  --martis-badge-warning-bg:      rgba(245, 158, 11, 0.15);
  --martis-badge-warning-text:    #fcd34d;
  --martis-badge-warning-border:  rgba(245, 158, 11, 0.3);
  --martis-badge-danger-bg:       rgba(239, 68, 68, 0.15);
  --martis-badge-danger-text:     #fca5a5;
  --martis-badge-danger-border:   rgba(239, 68, 68, 0.3);

  /* ▸ Border radius */
  --martis-radius-sm:     0.25rem;
  --martis-radius-md:     0.375rem;
  --martis-radius-lg:     0.5rem;
  --martis-radius-xl:     0.75rem;
  --martis-radius-full:   9999px;

  /* ▸ Typography — font families */
  --martis-font-sans:     'Inter var', 'Inter', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  --martis-font-mono:     'JetBrains Mono', 'Fira Code', ui-monospace, SFMono-Regular, Menlo, monospace;
  --martis-font-heading:  var(--martis-font-sans);

  /* ▸ Typography — font sizes (modular scale) */
  --martis-font-size-xs:    0.75rem;     /* 12px — tooltips, micro labels */
  --martis-font-size-sm:    0.875rem;    /* 14px — body, inputs, labels */
  --martis-font-size-base:  1rem;        /* 16px — base */
  --martis-font-size-lg:    1.125rem;    /* 18px — section headers */
  --martis-font-size-xl:    1.25rem;     /* 20px — card titles */
  --martis-font-size-2xl:   1.5rem;      /* 24px — page titles */
  --martis-font-size-3xl:   1.875rem;    /* 30px — dashboard metrics */

  /* ▸ Typography — font weights */
  --martis-font-weight-normal:    400;
  --martis-font-weight-medium:    500;
  --martis-font-weight-semibold:  600;
  --martis-font-weight-bold:      700;

  /* ▸ Typography — line heights */
  --martis-line-height-tight:    1.25;
  --martis-line-height-normal:   1.5;
  --martis-line-height-relaxed:  1.75;

  /* ▸ Chart palette (10 distinct colors) */
  --martis-chart-1:  #6366f1;
  --martis-chart-2:  #22c55e;
  --martis-chart-3:  #f59e0b;
  --martis-chart-4:  #ef4444;
  --martis-chart-5:  #8b5cf6;
  --martis-chart-6:  #06b6d4;
  --martis-chart-7:  #f97316;
  --martis-chart-8:  #ec4899;
  --martis-chart-9:  #14b8a6;
  --martis-chart-10: #a855f7;

  /* ▸ File icon colors */
  --martis-file-icon-pdf:     #ef4444;
  --martis-file-icon-doc:     #3b82f6;
  --martis-file-icon-xls:     #22c55e;
  --martis-file-icon-ppt:     #f97316;
  --martis-file-icon-zip:     #a855f7;
  --martis-file-icon-default: #6b7280;
}

/* ── Light Mode ──────────────────────────────────────────────── */
html:not(.dark) {
  /* ▸ Background layers */
  --martis-bg:            #f1f5f9;
  --martis-surface:       #ffffff;
  --martis-surface-alt:   #f1f5f9;
  --martis-sidebar:       #ffffff;
  --martis-topbar:        #ffffff;
  --martis-card:          #ffffff;
  --martis-input-bg:      #f8fafc;

  /* ▸ Borders */
  --martis-border:        #e2e8f0;

  /* ▸ Text */
  --martis-text:          #1e293b;
  --martis-text-muted:    #64748b;

  /* ▸ Accent */
  --martis-accent:        #6366f1;
  --martis-accent-hover:  #4f46e5;
  --martis-accent-active: #4338ca;
  --martis-accent-bg-light: rgba(99, 102, 241, 0.06);
  --martis-accent-bg:     rgba(99, 102, 241, 0.1);
  --martis-focus-ring:    rgba(99, 102, 241, 0.15);

  /* ▸ Semantic colors */
  --martis-success:       #16a34a;
  --martis-success-hover: #15803d;
  --martis-warning:       #d97706;
  --martis-warning-hover: #b45309;
  --martis-danger:        #dc2626;
  --martis-danger-hover:  #b91c1c;
  --martis-info:          #2563eb;
  --martis-info-hover:    #1d4ed8;

  /* ▸ Semantic backgrounds */
  --martis-success-bg:    #dcfce7;
  --martis-success-text:  #15803d;
  --martis-warning-bg:    #fef3c7;
  --martis-warning-text:  #92400e;
  --martis-danger-bg:     #fee2e2;
  --martis-danger-text:   #b91c1c;
  --martis-info-bg:       #dbeafe;
  --martis-info-text:     #1e40af;

  /* ▸ Interactive states */
  --martis-hover:         rgba(0, 0, 0, 0.04);
  --martis-active:        rgba(0, 0, 0, 0.08);

  /* ▸ Search overlay */
  --martis-search-bg:     rgba(0, 0, 0, 0.04);
  --martis-search-border: rgba(0, 0, 0, 0.12);

  /* ▸ Overlays & shadows */
  --martis-overlay:       rgba(0, 0, 0, 0.4);
  --martis-peek-shadow:   0 2px 8px rgba(0, 0, 0, 0.10);
  --martis-shadow-sm:     0 1px 2px rgba(0, 0, 0, 0.05);
  --martis-shadow-md:     0 4px 6px -1px rgba(0, 0, 0, 0.07), 0 2px 4px -1px rgba(0, 0, 0, 0.04);
  --martis-shadow-lg:     0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);

  /* ▸ DataTable */
  --martis-row-even:              rgba(248, 250, 252, 1);
  --martis-row-hover:             rgba(241, 245, 249, 1);
  --martis-table-header-bg:       rgba(99, 102, 241, 0.06);
  --martis-table-header-text:     #3730a3;
  --martis-table-header-border:   rgba(99, 102, 241, 0.25);

  /* ▸ Badge variants (legacy) */
  --martis-badge-info-bg:         #dbeafe;
  --martis-badge-info-text:       #1e40af;
  --martis-badge-info-border:     #bfdbfe;
  --martis-badge-success-bg:      #dcfce7;
  --martis-badge-success-text:    #15803d;
  --martis-badge-success-border:  #bbf7d0;
  --martis-badge-warning-bg:      #fef9c3;
  --martis-badge-warning-text:    #a16207;
  --martis-badge-warning-border:  #fde68a;
  --martis-badge-danger-bg:       #fee2e2;
  --martis-badge-danger-text:     #b91c1c;
  --martis-badge-danger-border:   #fecaca;

  /* ▸ Chart palette (light variants) */
  --martis-chart-1:  #6366f1;
  --martis-chart-2:  #16a34a;
  --martis-chart-3:  #d97706;
  --martis-chart-4:  #dc2626;
  --martis-chart-5:  #7c3aed;
  --martis-chart-6:  #0891b2;
  --martis-chart-7:  #ea580c;
  --martis-chart-8:  #db2777;
  --martis-chart-9:  #0d9488;
  --martis-chart-10: #9333ea;
}

CSS;
    }
}
