<?php

namespace Martis\Console;

use Illuminate\Console\Command;

class ThemeMakeCommand extends Command
{
    protected $signature = 'martis:theme {name? : The theme name (default: custom)}';

    protected $description = 'Scaffold a custom Martis theme with dark and light mode variables';

    public function handle(): int
    {
        /** @var string $name */
        $name = $this->argument('name') ?? 'custom';
        $name = strtolower((string) preg_replace('/[^a-zA-Z0-9_-]/', '-', $name));

        $dir = resource_path('css/martis');
        $path = $dir.'/'.$name.'.css';

        if (! is_dir($dir)) {
            mkdir($dir, 0755, true);
            $this->components->info('Created directory: resources/css/martis/');
        }

        if (file_exists($path) && ! $this->confirm("Theme '{$name}.css' already exists. Overwrite?")) {
            $this->components->warn('Aborted.');

            return self::FAILURE;
        }

        file_put_contents($path, $this->themeStub($name));
        $this->components->info("Theme created: resources/css/martis/{$name}.css");

        $this->components->twoColumnDetail('<fg=green>Next steps</>');
        $this->newLine();
        $this->line('  1. Edit the CSS variables in <comment>resources/css/martis/'.$name.'.css</comment>');
        $this->line('  2. Import it in your app CSS <comment>after</comment> the Martis styles:');
        $this->newLine();
        $this->line("     <comment>@import 'martis/resources/css/martis.css';</comment>");
        $this->line("     <comment>@import './css/martis/{$name}.css';</comment>");
        $this->newLine();
        $this->line('  3. Or set the theme in <comment>config/martis.php</comment>:');
        $this->newLine();
        $this->line("     <comment>'theme' => '{$name}',</comment>");
        $this->newLine();

        return self::SUCCESS;
    }

    private function themeStub(string $name): string
    {
        return <<<CSS
/*
 * Martis Theme: {$name}
 *
 * Override the default Martis CSS variables for both dark and light modes.
 * Import this file AFTER martis.css in your app's CSS pipeline.
 *
 * All Martis components use these variables, so changing a value here
 * will propagate across the entire admin panel automatically.
 *
 * Generated by: php artisan martis:theme {$name}
 */

/* ── Dark Mode (default) ─────────────────────────────────────── */
:root {
  /* Background layers */
  --martis-bg:            #1b2332;   /* Page background */
  --martis-surface:       #1e293b;   /* Cards, panels */
  --martis-sidebar:       #111827;   /* Sidebar background */
  --martis-topbar:        #1e293b;   /* Top navigation bar */
  --martis-card:          #1e293b;   /* Card components */
  --martis-input-bg:      #111827;   /* Form input backgrounds */

  /* Borders */
  --martis-border:        #334155;   /* Default border color */

  /* Text */
  --martis-text:          #e2e8f0;   /* Primary text */
  --martis-text-muted:    #94a3b8;   /* Secondary/placeholder text */

  /* Accent (brand color) */
  --martis-accent:        #6366f1;   /* Primary accent (buttons, links, highlights) */
  --martis-accent-hover:  #4f46e5;   /* Accent hover state */

  /* Interactive states */
  --martis-hover:         rgba(255, 255, 255, 0.05);  /* Hover background */
  --martis-active:        rgba(255, 255, 255, 0.1);   /* Active/pressed background */

  /* Search overlay */
  --martis-search-bg:     rgba(255, 255, 255, 0.06);
  --martis-search-border: rgba(255, 255, 255, 0.1);

  /* DataTable */
  --martis-row-even:      rgba(30, 41, 59, 0.5);      /* Striped even row */
  --martis-row-hover:     rgba(51, 65, 85, 0.5);      /* Row hover */
}

/* ── Light Mode ──────────────────────────────────────────────── */
html:not(.dark) {
  /* Background layers */
  --martis-bg:            #f1f5f9;
  --martis-surface:       #ffffff;
  --martis-sidebar:       #ffffff;
  --martis-topbar:        #ffffff;
  --martis-card:          #ffffff;
  --martis-input-bg:      #f8fafc;

  /* Borders */
  --martis-border:        #e2e8f0;

  /* Text */
  --martis-text:          #1e293b;
  --martis-text-muted:    #64748b;

  /* Accent (brand color) — same by default, customize if needed */
  --martis-accent:        #6366f1;
  --martis-accent-hover:  #4f46e5;

  /* Interactive states */
  --martis-hover:         rgba(0, 0, 0, 0.04);
  --martis-active:        rgba(0, 0, 0, 0.08);

  /* Search overlay */
  --martis-search-bg:     rgba(0, 0, 0, 0.04);
  --martis-search-border: rgba(0, 0, 0, 0.12);

  /* DataTable */
  --martis-row-even:      rgba(248, 250, 252, 1);
  --martis-row-hover:     rgba(241, 245, 249, 1);
}

/*
 * Custom component overrides — add below.
 * You can target any PrimeReact or Martis component:
 *
 * .martis-datatable thead th {
 *   border-bottom-color: var(--martis-accent);
 * }
 *
 * .p-button {
 *   border-radius: 9999px;
 * }
 */

CSS;
    }
}
