<?php

namespace Martis\Console;

use Illuminate\Console\Command;

class ThemeMakeCommand extends Command
{
    protected $signature = 'martis:theme {name? : The theme name (default: custom)}';

    protected $description = 'Scaffold a custom Martis theme with dark and light mode variables';

    /**
     * Handle.
     */
    public function handle(): int
    {
        /** @var string $name */
        $name = $this->argument('name') ?? 'custom';
        $name = strtolower((string) preg_replace('/[^a-zA-Z0-9_-]/', '-', $name));

        // 1. Create source CSS in resources/
        $dir = resource_path('css/martis');
        $path = $dir.'/'.$name.'.css';

        if (! is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        if (file_exists($path) && ! $this->confirm("Theme '{$name}.css' already exists. Overwrite?")) {
            $this->components->warn('Aborted.');

            return self::FAILURE;
        }

        file_put_contents($path, $this->themeStub($name));
        $this->components->info("Theme created: resources/css/martis/{$name}.css");

        // 2. Publish to public/vendor/martis/themes/
        $publicDir = public_path('vendor/martis/themes');
        if (! is_dir($publicDir)) {
            mkdir($publicDir, 0755, true);
        }
        copy($path, $publicDir.'/'.$name.'.css');
        $this->components->info("Published to: public/vendor/martis/themes/{$name}.css");

        // 3. Update config/martis.php theme.name
        $configPath = config_path('martis.php');
        if (file_exists($configPath)) {
            $configContent = file_get_contents($configPath);

            if ($configContent === false) {
                return self::SUCCESS;
            }

            if (str_contains($configContent, "'name' =>")) {
                // Update existing name value
                $configContent = (string) preg_replace(
                    "/('name'\s*=>\s*)(env\([^)]+\)|'[^']*'|null)/",
                    "'{$name}'",
                    $configContent,
                    1 // only first occurrence within theme block
                );
            } else {
                // Add name key after allowToggle line
                $configContent = (string) preg_replace(
                    "/(\s*'allowToggle'\s*=>.*?,)/",
                    "\n        'name' => '{$name}',",
                    $configContent
                );
            }

            file_put_contents($configPath, (string) $configContent);
            $this->components->info("Config updated: config/martis.php theme.name = '{$name}'");
        }

        $this->newLine();
        $this->components->twoColumnDetail('<fg=green>Done</>');
        $this->newLine();
        $this->line('  1. Edit the CSS variables in <comment>public/vendor/martis/themes/'.$name.'.css</comment>');
        $this->line('  2. Changes take effect immediately (plain CSS, no rebuild needed).');
        $this->line('  3. Or change theme in <comment>config/martis.php</comment>:');
        $this->newLine();
        $this->line("     <comment>'theme' => ['name' => '{$name}']</comment>");
        $this->newLine();
        $this->line('  To revert to default theme: set name to null in config.');
        $this->newLine();

        return self::SUCCESS;
    }

    private function themeStub(string $name): string
    {
        return <<<CSS
/*
 * Martis Theme: {$name}
 *
 * Every CSS variable used by Martis is listed below.
 * Edit any value and re-run: php artisan martis:theme {$name}
 *
 * Generated by: php artisan martis:theme {$name}
 */

/* ── Dark Mode (default) ─────────────────────────────────────── */
:root {
  /* ▸ Background layers */
  --martis-bg:            #1b2332;   /* Page background */
  --martis-surface:       #1e293b;   /* Cards, panels, modals */
  --martis-surface-alt:   #283548;   /* Alternate surface (zebra, secondary panels) */
  --martis-sidebar:       #111827;   /* Sidebar background */
  --martis-topbar:        #1e293b;   /* Top navigation bar */
  --martis-card:          #1e293b;   /* Card components */
  --martis-input-bg:      #111827;   /* Form input backgrounds */

  /* ▸ Borders */
  --martis-border:        #334155;   /* Default border color */

  /* ▸ Text */
  --martis-text:          #e2e8f0;   /* Primary text */
  --martis-text-muted:    #94a3b8;   /* Secondary / placeholder text */

  /* ▸ Accent (brand color — buttons, links, focus rings) */
  --martis-accent:        #6366f1;
  --martis-accent-hover:  #4f46e5;

  /* ▸ Interactive states */
  --martis-hover:         rgba(255, 255, 255, 0.05);
  --martis-active:        rgba(255, 255, 255, 0.1);

  /* ▸ Search overlay */
  --martis-search-bg:     rgba(255, 255, 255, 0.06);
  --martis-search-border: rgba(255, 255, 255, 0.1);

  /* ▸ Peek / preview popover */
  --martis-peek-shadow:   0 2px 8px rgba(0, 0, 0, 0.20);

  /* ▸ DataTable */
  --martis-row-even:              rgba(30, 41, 59, 0.5);
  --martis-row-hover:             rgba(51, 65, 85, 0.5);
  --martis-table-header-bg:       rgba(99, 102, 241, 0.1);
  --martis-table-header-text:     #c7d2fe;
  --martis-table-header-border:   rgba(99, 102, 241, 0.35);

  /* ▸ Badge variants */
  --martis-badge-info-bg:         rgba(99, 102, 241, 0.15);
  --martis-badge-info-text:       #a5b4fc;
  --martis-badge-info-border:     rgba(99, 102, 241, 0.3);
  --martis-badge-success-bg:      rgba(34, 197, 94, 0.15);
  --martis-badge-success-text:    #86efac;
  --martis-badge-success-border:  rgba(34, 197, 94, 0.3);
  --martis-badge-warning-bg:      rgba(245, 158, 11, 0.15);
  --martis-badge-warning-text:    #fcd34d;
  --martis-badge-warning-border:  rgba(245, 158, 11, 0.3);
  --martis-badge-danger-bg:       rgba(239, 68, 68, 0.15);
  --martis-badge-danger-text:     #fca5a5;
  --martis-badge-danger-border:   rgba(239, 68, 68, 0.3);
}

/* ── Light Mode ──────────────────────────────────────────────── */
html:not(.dark) {
  /* ▸ Background layers */
  --martis-bg:            #f1f5f9;
  --martis-surface:       #ffffff;
  --martis-surface-alt:   #f1f5f9;
  --martis-sidebar:       #ffffff;
  --martis-topbar:        #ffffff;
  --martis-card:          #ffffff;
  --martis-input-bg:      #f8fafc;

  /* ▸ Borders */
  --martis-border:        #e2e8f0;

  /* ▸ Text */
  --martis-text:          #1e293b;
  --martis-text-muted:    #64748b;

  /* ▸ Accent */
  --martis-accent:        #6366f1;
  --martis-accent-hover:  #4f46e5;

  /* ▸ Interactive states */
  --martis-hover:         rgba(0, 0, 0, 0.04);
  --martis-active:        rgba(0, 0, 0, 0.08);

  /* ▸ Search overlay */
  --martis-search-bg:     rgba(0, 0, 0, 0.04);
  --martis-search-border: rgba(0, 0, 0, 0.12);

  /* ▸ Peek / preview popover */
  --martis-peek-shadow:   0 2px 8px rgba(0, 0, 0, 0.10);

  /* ▸ DataTable */
  --martis-row-even:              rgba(248, 250, 252, 1);
  --martis-row-hover:             rgba(241, 245, 249, 1);
  --martis-table-header-bg:       rgba(99, 102, 241, 0.06);
  --martis-table-header-text:     #3730a3;
  --martis-table-header-border:   rgba(99, 102, 241, 0.25);

  /* ▸ Badge variants */
  --martis-badge-info-bg:         #dbeafe;
  --martis-badge-info-text:       #1e40af;
  --martis-badge-info-border:     #bfdbfe;
  --martis-badge-success-bg:      #dcfce7;
  --martis-badge-success-text:    #15803d;
  --martis-badge-success-border:  #bbf7d0;
  --martis-badge-warning-bg:      #fef9c3;
  --martis-badge-warning-text:    #a16207;
  --martis-badge-warning-border:  #fde68a;
  --martis-badge-danger-bg:       #fee2e2;
  --martis-badge-danger-text:     #b91c1c;
  --martis-badge-danger-border:   #fecaca;
}

CSS;
    }
}
